---
title: "AquaMaps by BOEM area"
author: "Ben Best"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)
```

## `aquamaps`

* [https://raquamaps.github.io](https://raquamaps.github.io/)
* [https://raquamaps.github.io/raquamaps-intro.html](https://raquamaps.github.io/raquamaps-intro.html)
* [Curated Data From AquaMaps.Org • aquamapsdata](https://raquamaps.github.io/aquamapsdata/index.html)

```{r}
# dependency for aquamapsdata:
#  - Terminal: brew install gnupg
#  - R: install.packages("rcrypt")
librarian::shelf(
  raquamaps/aquamapsdata,
  DBI, dplyr, librarian, mapview,
  raquamaps/raquamaps,
  sf, terra, zeallot)

# downloads about 2 GB of data, approx 10 GB when unpacked
# download_db()


# data(package = "raquamaps")
con_sl <- default_db("sqlite") # /Users/bbest/Library/Application Support/aquamaps/am.db
dbListTables(con_sl)
```

```
 [1] "fts"                 "fts_config"          "fts_content"        
 [4] "fts_data"            "fts_docsize"         "fts_idx"            
 [7] "hcaf_r"              "hcaf_species_native" "hspen_r"            
[10] "occurrencecells_r"   "speciesoccursum_r"  
````

```{r}
# get cells and species list per region
t_hcaf <- tbl(con_sl, "hcaf_r")

pts_hcaf <- t_hcaf %>% 
  select(ID, CsquareCode, CenterLong, CenterLat) %>% 
  collect() %>% 
  st_as_sf(
    coords = c("CenterLong", "CenterLat"), crs = 4326)

r_g <- rast(
  xmin=-180, xmax=180, ymin=-90, ymax=90, 
  resolution = c(0.5))

r_hcaf <- rasterize(pts_hcaf, r_g, field = "ID")

ply_hcaf <- as.polygons(r_hcaf) %>% 
  st_as_sf() %>% 
  rename(ID = "lyr.1") %>%
  left_join(
    pts_hcaf %>% 
      st_drop_geometry() %>% 
      select(ID, CsquareCode), 
    by = "ID") %>% 
  select(-ID)

# BOEM region
brgn <- "CGM"
ply_brgns_geo <- "data/ply_boem_rgns.geojson"
ply_brgns <- read_sf(ply_brgns_geo) %>% 
  rename(brgn = MMS_PLAN_A)
ply_brgn <- ply_brgns %>% 
  filter(brgn == !!brgn)
# mapView(ply_brgn)

ply_hcaf_brgn <- st_intersection(
  ply_hcaf, 
  ply_brgn %>% 
    select(geometry))

mapview(ply_hcaf_brgn)

tbl(con, "hcaf_r") %>% 
  filter(ID == 212279) %>% 
  pull(CsquareCode) # "7208:456:4"

c(x1, y1, x2, y2) %<-% st_bbox(ply_hcaf_brgn) %>% as.numeric()

# brew services start postgresql
# brew services stop postgresql

con_pg <- DBI::dbConnect(
  RPostgres::Postgres(),
  dbname   = "am",
  host     = "localhost",
  port     = 5432)
dbListTables(con_pg)

# write from sqlite to postgresql database
# tbl <- "hcaf_species_native"
# d <- dbReadTable(con_sl, tbl)
# dbWriteTable(con_pg, tbl, d)

# create indexes
dbSendQuery(
  con_pg, 
  'CREATE INDEX IF NOT EXISTS hcaf_species_native_CenterLong_idx ON hcaf_species_native("CenterLong")')
dbSendQuery(
  con_pg, 
  'CREATE INDEX IF NOT EXISTS hcaf_species_native_CenterLat_idx ON hcaf_species_native("CenterLat")')
dbSendQuery(
  con_pg, 
  'CREATE INDEX IF NOT EXISTS hcaf_species_native_CsquareCode_idx ON hcaf_species_native("CsquareCode")')

# summarize in postgres (1.7 sec vs 4.1 min in sqlite)

c_spp <- tbl(con_pg, "hcaf_species_native") %>% 
  filter(
    CenterLong  >= x1,
    CenterLong  <= x2,
    CenterLat   >= y1,
    CenterLat   <= y2,
    Probability >= 0.5) %>% 
  group_by(CsquareCode) %>% 
  summarize(
    n_spp = n()) %>% 
  collect() %>% 
  filter(
    CsquareCode %in% ply_hcaf_brgn$CsquareCode) %>% 
  mutate(
    n_spp = as.integer(n_spp))

p <- ply_hcaf_brgn %>% 
  left_join(
    c_spp,
    by = "CsquareCode")
mapview(p, zcol="n_spp")
```


## aquamaps usage (old)

```{r}
# fuzzy search allows full text search operators AND, OR, NOT and +
# see https://www.sqlitetutorial.net/sqlite-full-text-search/
am_search_fuzzy(search_term = "trevally") %>% pull(key)

# exact search without parameters returns all results
nrow(am_search_exact())

# exact search giving NULL params shows examples of existing values
# here we see what combinations are present in the dataset for 
# angling, diving, dangerous, highseas, deepwater organisms
am_search_exact(
  angling = NULL, diving = NULL, dangerous = NULL, 
  deepwater = NULL, highseas = NULL, m_invertebrates = NULL)

# exact search without NULL params, specifying values
hits <- 
  am_search_exact(angling = 1, diving = 1, dangerous = 0)

# display results
display <- 
  hits %>% mutate(binomen = paste(Genus, Species)) %>%
  select(SpeciesID, binomen, SpecCode, FBname)

knitr::kable(display)
```

### Species maps

```{r}
librarian::shelf(
  aquamapsdata, leaflet, raster)

# get the identifier for the species
key <- am_search_fuzzy("bluespotted")$key
ras <- am_raster(key)

# show the native habitat map
am_map_leaflet(ras, title = "Bluespotted trevally") %>%
  leaflet::fitBounds(lng1 = 100, lat1 = -46, lng2 = 172, lat2 = -2)
```

### Biodiversity Maps

```{r}
keys <- am_search_exact(Genus = "Caranx")$SpeciesID

ras <- am_raster(keys, fun = "count")

am_map_leaflet(ras, title = "Caranx") %>%
  leaflet::fitBounds(lng1 = 100, lat1 = -46, lng2 = 172, lat2 = -2)

am_citation("md")
```

### Locations in cells and the half degree cell “authority file” table

```{r}
am_hcaf() %>% head(1) %>% collect() %>% names()

# compute depth across all cells
am_hcaf() %>% 
  summarize(depth = mean(DepthMean, na.rm = TRUE)) %>% 
  collect() %>% 
  pull(depth)

# cells with a depth value larger than 4000
deepwater <- 
  am_hcaf() %>% filter(DepthMean > 4000) %>% pull(CsquareCode)

# some of the on average deepest locations
deepwater

# species likely to occur in deepwater location(s)
deepwater_species <- am_species_in_csc(deepwater, min_prob = 0.5) # SLOW! # tibble: 16,266 × 2
deepwater_species

dplyr::tbl("hcaf_species_native")

key <- deepwater_species$SpeciesID[2:4] # 1st: "W-Msc-342354" Error: near "W": syntax error
am_search_exact(SpeciesID = key[1])
```

### Species preferences or environmental envelope

```{r}
# use one or more keys for species
key <- deepwater_species$SpeciesID[2]
am_hspen() %>% filter(SpeciesID == key) %>% head(1) %>% collapse%>% glimpse()
```


```
Rows: ??
Columns: 56
Database: sqlite 3.39.3 [/Users/bbest/Library/Application Support/aquamaps/am.db]
$ SpeciesID       <chr> "Fis-24154"
$ Speccode        <int> 2735
$ LifeStage       <chr> "adults"
$ FAOAreas        <chr> "21, 27, 31, 34, 41, 47, 48, 51, 57, 61, 67, 71, 77, 81, 87"
$ FAOComplete     <int> NA
$ NMostLat        <dbl> 55
$ SMostLat        <dbl> -61
$ WMostLong       <dbl> NA
$ EMostLong       <dbl> NA
$ DepthYN         <int> 1
$ DepthMin        <int> 777
$ DepthPrefMin    <int> 952
$ DepthPrefMax    <int> 1350
$ DepthMax        <int> 2121
$ MeanDepth       <int> 0
$ Pelagic         <int> 1
$ TempYN          <int> 1
$ TempMin         <dbl> -1.21
$ TempPrefMin     <dbl> 1.03
$ TempPrefMax     <dbl> 6.29
$ TempMax         <dbl> 28.94
$ SalinityYN      <int> 1
$ SalinityMin     <dbl> 33.08
$ SalinityPrefMin <dbl> 34.33
$ SalinityPrefMax <dbl> 35.33
$ SalinityMax     <dbl> 37.32
$ PrimProdYN      <int> 1
$ PrimProdMin     <dbl> -0.67
$ PrimProdPrefMin <dbl> 0.33
$ PrimProdPrefMax <dbl> 15.27
$ PrimProdMax     <dbl> 67.43
$ IceConYN        <int> 1
$ IceConMin       <dbl> -1
$ IceConPrefMin   <dbl> 0
$ IceConPrefMax   <dbl> 0
$ IceConMax       <dbl> 0
$ OxyYN           <int> 1
$ OxyMin          <dbl> 1.96
$ OxyPrefMin      <dbl> 128.98
$ OxyPrefMax      <dbl> 265.24
$ OxyMax          <dbl> 400.38
$ LandDistYN      <int> 0
$ LandDistMin     <dbl> 1
$ LandDistPrefMin <dbl> 98
$ LandDistPrefMax <dbl> 1181
$ LandDistMax     <dbl> 2057
$ Remark          <chr> "FAO areas,bounding box and/or pelagic flag based on last review."
$ DateCreated     <chr> "2020-04-26 00:00:00"
$ DateModified    <chr> NA
$ expert_id       <int> NA
$ DateExpert      <chr> NA
$ Layer           <chr> "b"
$ Rank            <int> 1
$ MapOpt          <int> 1
$ ExtnRuleYN      <int> 1
$ Reviewed        <int> NA
```

## BOEM areas

```{r}
# variables




```

